// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CollectPersonsFilter struct {
	OlderThan   *int     `json:"olderThan,omitempty"`
	YoungerThan *int     `json:"youngerThan,omitempty"`
	Gender      *string  `json:"gender,omitempty"`
	Nations     []string `json:"nations,omitempty"`
}

type CreatePersonInput struct {
	Name       string `json:"name"`
	Surname    string `json:"surname"`
	Patronymic string `json:"patronymic"`
}

type CreatePersonResponse struct {
	Success  bool   `json:"success"`
	PersonID string `json:"personId"`
}

type DeletePersonInput struct {
	PersonID string `json:"personId"`
}

type DeletePersonResponse struct {
	Success bool `json:"success"`
}

type Person struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Surname    string `json:"surname"`
	Patronymic string `json:"patronymic"`
	Nation     string `json:"nation"`
	Gender     string `json:"gender"`
	Age        int    `json:"age"`
}

type UpdatePersonInput struct {
	PersonID  string  `json:"personId"`
	NewNation *string `json:"newNation,omitempty"`
	NewGender *string `json:"newGender,omitempty"`
	NewAge    *int    `json:"newAge,omitempty"`
}

type UpdatePersonResponse struct {
	Success bool `json:"success"`
}
